version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile.dev
      target: development
    ports:
      - "4200:4200"
    volumes:
      - ./front:/app
    environment:
      - NODE_ENV=development
      - API_URL=http://backend:3000
    depends_on:
      - backend

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile.dev
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./back:/app
    environment:
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=admin
      - DATABASE_NAME=mydatabase

  database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=mydatabase
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - rabbitmq-dev-data:/var/lib/rabbitmq

volumes:
  postgres-dev-data:
  rabbitmq-dev-data: