# Production
FROM node:18-alpine as production-build
WORKDIR /usr/local/app
COPY ./ /usr/local/app/
RUN npm install
RUN npm run build --prod

FROM nginx:latest as production
COPY --from=production-build /usr/local/app/dist/fr-administration-front /usr/share/nginx/html
COPY ../nginx/nginx.conf /etc/nginx/nginx.conf